name: karmalab_assignment
description: A new Flutter project.



publish_to: 'none'
version: 1.0.0+1



environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2



  hive: ^2.2.3
  email_validator: ^3.0.0
  flutter_animate: ^4.5.0
  logger: ^2.1.0
  connectivity_plus: ^6.0.4
  animated_text_kit: ^4.2.2
  timeline_tile: ^2.0.0
  loading_animation_widget: ^1.2.0
  smooth_page_indicator: ^1.1.0
  iconsax: ^0.0.8
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  flutter_native_splash: ^2.4.2






  get: ^4.6.5
  get_thumbnail_video: ^0.6.1
  dio: ^5.6.0
  carousel_slider_plus: ^7.0.1
  awesome_dialog: ^3.2.1
  flutter_switch: ^0.3.2
  flutter_3d_controller: ^1.3.1
  url_launcher: ^6.1.14
  uni_links: ^0.5.1
  hive_flutter: ^1.1.0
  #video_thumbnail: ^0.5.3
  flutter_staggered_grid_view: ^0.7.0
  sliding_up_panel: ^2.0.0+1
  path_provider: ^2.1.4
  flutter_toggle_tab: ^1.0.7
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  remix: ^0.0.1-dev.1
  remixicon: ^1.0.0
  pinput: ^5.0.0
  http: ^1.2.2
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  flutter_animated_button: ^2.0.3
  fl_chart: ^0.68.0
  lottie: ^3.1.2
  flutter_charts: ^0.5.2
  flutter_web_auth: ^0.5.0
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  google_sign_in: ^6.2.1
  flutter_slidable: ^3.1.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.0
  super_drag_and_drop: ^0.8.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logos/ic_launcher-2/1024.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^1.0.0
  build_runner: ^2.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/animations/
    - assets/images/logos/
    - assets/images/lottie/
    - assets/images/png/onboarding-images/
    - assets/images/png/
    - assets/images/logos/ic_launcher-2/
































